org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=26.2
fabricloader_version=0.19.3
minecraft_dependency=>=26.2

yacl_version=3.9.5
yacl_fabric=26.2-fabric
modmenu_version=20.0.1

mod_version=10.1.1-alpha
maven_group=crimsonedgehope.minecraft.fabric

modrinth_project_id=PtUSravz
modrinth_gameversions=26.2
github_repository=https://github.com/CrimsonEdgeHope/SocksProxyClientOfMinecraft

archives_base_name=SocksProxyClient
mod_id=socksproxyclient
